class_name Opcodes
extends Object

static var dbase100: Dictionary = {
	0: {"name": "InventoryDocumentImage", "desc": "for notes/maps/etc, the image to show after initial animation"},
	1: {"name": "If flag set, continue", "desc": "Continue chain if flag is set"},
	2: {"name": "If item count above, continue", "desc": "first two bytes represent the item index to check. the third byte represents the number to do a \"greater than\" comparison against."},
	4: {"name": "Set flag", "desc": "Set a flag"},
	5: {"name": "Play audio dialog", "desc": "DBase400 Offset"},
	7: {"name": "Play video", "desc": "Cutscene index from DBASE100"},
	8: {"name": "Choice String", "desc": "DBASE400 offset"},
	9: {"name": "Start Choice", "desc": "The commands between a start and end choice will be run after selecting a Choice String"},
	10: {"name": "End Choice", "desc": "End a choice section"},
	11: {"name": "Start Random", "desc": "Start a random selection"},
	12: {"name": "End Random", "desc": "End a random selection"},
	13: {"name": "If flag set, then next command", "desc": "Only execute next command if flag is set"},
	14: {"name": "DisplayTexture", "desc": "Displays a texture onscreen (DBASE300 Offset / 8)"},
	15: {"name": "SetInformationTopic", "desc": "used with the 0x01 trigger code to set up discussion topics when examining an item. value is the index (must confirm) to a string interface which will be displayed when the \"i\" button is pressed in inventory. when the topic is pressed, the contained command chain is run"},
	16: {"name": "ChangeName", "desc": "used with the 0x02 trigger to change the name of an item (usually with some flag; if so call 0x01 AFTER this one). the value is the index (must confirm) of the string/interface"},
	17: {"name": "Give item", "desc": "Item index"},
	18: {"name": "WeaponAnimation", "desc": "The passive and attacking weapon animation. Offset to the animation"},
	19: {"name": "SetWeaponBullet", "desc": "the item ID of the bullet to associate with a weapon"},
	20: {"name": "SetAmmoCap", "desc": "sets the max ammo before the weapon needs to be reloaded"},
	21: {"name": "MaxDamage", "desc": "For bullet, the max damage it will do (anywhere from 0.5x - 1.0x)"},
	22: {"name": "TravelSpeed", "desc": "For bullet, the speed it travels at"},
	23: {"name": "BulletHitAnimation", "desc": "For bullet, the texture to change to upon impact (index? but doesn't appear in DEMO.DAS or ADEMO.DAS)"},
	24: {"name": "WeaponBulletDelay", "desc": "For weapon, the delay after firing to spawn the bullet object"},
	25: {"name": "Play SFX", "desc": "Index from FXSCRIPT.SFX"},
	26: {"name": "Change Music", "desc": "DBase300 Offset / 8"},
	28: {"name": "?", "desc": "Always 16777215 (0xFFFFFF)"},
	29: {"name": "Jump to different command", "desc": "DBASE100 command index"},
	31: {"name": "?", "desc": "None"},
	32: {"name": "WeaponAmmoRecharge", "desc": "the inventory index of the ammo refill. when second byte is 80, it's a rechargeable weapon and the first byte represents ammo recharge rate"},
	33: {"name": "?", "desc": "None"},
	35: {"name": "MapCommandIndexCallback", "desc": "Performs a script from the current .RAW map file. value is the command index"},
	36: {"name": "SetMonsterMoveSpeed", "desc": "Set the move speed of a monster"},
	37: {"name": "MonsterPathingFlag?", "desc": "Slightly influencing a monster's movement/pathing"},
	38: {"name": "SetHealthOrHeal", "desc": "Initializes max health of a monster or heals by value (when a value of 0x8002 or 0xE0C0 is provided, the game's main menu is displayed)"},
	39: {"name": "BulletImmunity", "desc": "For a monster, sets the immunity against a bullet by index (bullet does no damage)"},
	40: {"name": "SetMonsterBullet", "desc": "sets the bullet for a monster's primary attack"},
	41: {"name": "MonsterRoamingSFX", "desc": "sets the sound effect to play during monster roam (multiple can be set with multiple calls)"},
	42: {"name": "MonsterPrimAttackSFX", "desc": "sets the sound effect to play when monster makes its primary attack"},
	43: {"name": "MonsterPrimAttackDelay", "desc": "the delay to spawn the bullet for a monster's primary attack"},
	44: {"name": "WeaponAnimationSpeed", "desc": "for a weapon, modifies the animation play speed (directly impacts fire rate)"},
	45: {"name": "?", "desc": "Only 1,4, or 7 (also used when initializing: weapons = 0x05, monsters = 0x02 or 0x03)"},
	46: {"name": "SetBulletDuration", "desc": "for a bullet, the amount of time before it despawns. Used for all melee attacks."},
	48: {"name": "FlashScreen", "desc": "Flashes the environment. First darkness then brightness. Value is the intensity"},
	49: {"name": "MonsterDeathSFX", "desc": "the sound effect to play when the monster dies (but not critically dies, see 0xB1)"},
	50: {"name": "MonsterSpawnSFX", "desc": "the sound effect to play when the monster spawns"},
	51: {"name": "WeaponIconUI", "desc": "Which icon to display on screen for an equipped weapon (0x0A is unused Mace)"},
	52: {"name": "CombineWithItem", "desc": "set during the OnUse trigger (0x0b) and makes the current item combinable with another item whose index is the argument required for this command. run 0xB4 after this to set the item that the two will be replaced with"},
	53: {"name": "Dbase100CommandCallback", "desc": "performs a dbase100 command corresponding to its index"},
	54: {"name": "MapCommandIDCallback", "desc": "Performs a script from the current .RAW map file. value is the command ID"},
	83: {"name": "?", "desc": "None"},
	129: {"name": "If flag not set, continue", "desc": "Flag"},
	130: {"name": "If item count <=, continue", "desc": "checks if the count of an item id in inventory is less than or equal to a certain number and continues if so. first two bytes represent the item index to check. the third byte represents the number to do a \"less than or equal\" comparison against."},
	131: {"name": "If item count equal, continue", "desc": "checks if the count of an item id in inventory is equal to a certain amount. first two bytes represent the item index to check. the third byte represents the amount to compare with"},
	132: {"name": "Unset flag", "desc": "Flag"},
	141: {"name": "If not flag set, next command", "desc": "Only execute next command if flag is not set"},
	145: {"name": "Remove Item", "desc": "Item Index"},
	156: {"name": "ExitCommand", "desc": "always FF FF FF; used to end a command flow's execution"},
	158: {"name": "?", "desc": "None"},
	162: {"name": "Weapon X screen offset", "desc": "offsets the weapon's onscreen horizontal position (affects where projectile is fired)"},
	167: {"name": "BulletVulnerable", "desc": "For a monster, set vulnerability against a bullet (bullet does 2x damage). this can stack"},
	168: {"name": "SetMonsterSecondaryBullet", "desc": "sets the bullet for a monster's secondary attack"},
	169: {"name": "OnMonsterDamageSFX", "desc": "For a monster, what sound effect to play on damage (when run multiple times, randomly chooses one) (bugged? when multiple are selected, will not play the last one? need to add it twice)"},
	170: {"name": "MonsterSecondAttackSFX", "desc": "the sound effect to play when monster makes its secondary attack"},
	171: {"name": "MonsterSecondAttackDelay", "desc": "the delay to spawn the bullet for a monster's secondary attack"},
	177: {"name": "MonsterCritDeathSFX", "desc": "The sound effect to play when monster critically dies (like from max health in a single hit)"},
	178: {"name": "?", "desc": "None"},
	180: {"name": "SetCombinedItem", "desc": "used after command 0x34 to determine the final item when two items are combined. value is the item index of the final result item. When no 0x34 command is used, the item can be combined with itself (ie, used)."},
}

static var triggers: Dictionary = {
	1: {"name": "OnInformation", "desc": "Description"},
	2: {"name": "ChangeName", "desc": "this executes whenever the item is hovered over in the inventory and is used to change the name of an item (via the 0x10 command).
Like the 0x01 trigger code, it can be controlled via the 0x01 conditional command (when placed after the first command).
Note: although only the 0x10 command is used to change the name, other commands can be used."},
	4: {"name": "OnInspect", "desc": "command chain triggers when item is inspected (right click in the environment or magnifying glass in inventory)"},
	5: {"name": "WeaponAction", "desc": "commands initialize data for when the weapon is fired"},
	6: {"name": "AsBullet", "desc": "commands initialize data for when the item is used as a projectile"},
	7: {"name": "Document", "desc": "allows the inventory item to display a document image (using command code 0x00)"},
	10: {"name": "AsMonster", "desc": "initializes data for the item as a monster (also for Adam)"},
	11: {"name": "OnUse", "desc": "commands here initialize callbacks (other command chains) that run when the item is used"},
}
